ARG IMAGE_NAME
FROM ${IMAGE_NAME}:temp

RUN GOLANG_VERSION=1.10.5 \
 && DIGEST='a035d9beda8341b645d3f45a1b620cf2d8fb0c5eb409be36b389c0fd384ecc3a' \
 && wget -O go.tgz "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
 && echo "${DIGEST} *go.tgz" | sha256sum -c - \
 &&	tar -C /usr/local -xzf go.tgz \
 && rm go.tgz \
 && export PATH="/usr/local/go/bin:$PATH" \
 && go version

ONBUILD ARG REPOSITORY
ONBUILD ARG PACKAGE
ONBUILD ARG CGO_ENABLED
ONBUILD ENV CGO_ENABLED=${CGO_ENABLED} \
            PACKAGE=${PACKAGE}
ONBUILD WORKDIR /go/src/${REPOSITORY}/
ONBUILD COPY . .
ONBUILD RUN /loader -o /app "${PACKAGE:-}"
