ARG IMAGE_NAME
FROM ${IMAGE_NAME}:temp

RUN GOLANG_VERSION=1.10.6 \
 && DIGEST='acbdedf28b55b38d2db6f06209a25a869a36d31bdcf09fd2ec3d40e1279e0592' \
 && wget -O go.tgz "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
 && echo "${DIGEST} *go.tgz" | sha256sum -c - \
 &&	tar -C /usr/local -xzf go.tgz \
 && rm go.tgz \
 && export PATH="/usr/local/go/bin:$PATH" \
 && go version

ONBUILD ARG REPOSITORY
ONBUILD ARG PACKAGE
ONBUILD ARG CGO_ENABLED
ONBUILD ENV CGO_ENABLED=${CGO_ENABLED} \
            PACKAGE=${PACKAGE}
ONBUILD WORKDIR /go/src/${REPOSITORY}/
ONBUILD COPY . .
ONBUILD RUN /loader -o /app "${PACKAGE:-}"
