ARG IMAGE_NAME
FROM ${IMAGE_NAME}:temp

RUN GOLANG_VERSION=1.10.7 \
 && DIGEST='1aabe10919048822f3bb1865f7a22f8b78387a12c03cd573101594bc8fb33579' \
 && wget -O go.tgz "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
 && echo "${DIGEST} *go.tgz" | sha256sum -c - \
 &&	tar -C /usr/local -xzf go.tgz \
 && rm go.tgz \
 && export PATH="/usr/local/go/bin:$PATH" \
 && go version

ONBUILD ARG GOARCH
ONBUILD ENV GOARCH=$GOARCH
ONBUILD ARG REPOSITORY
ONBUILD WORKDIR /go/src/${REPOSITORY}/
ONBUILD COPY . .
ONBUILD ARG PACKAGE
ONBUILD ARG CGO_ENABLED
ONBUILD ENV CGO_ENABLED=${CGO_ENABLED} \
            PACKAGE=${PACKAGE}
ONBUILD RUN /loader -o /app "${PACKAGE:-}"
