ARG IMAGE_NAME
FROM ${IMAGE_NAME}:temp

RUN GOLANG_VERSION=1.11.3 \
 && DIGEST='d20a4869ffb13cee0f7ee777bf18c7b9b67ef0375f93fac1298519e0c227a07f' \
 && wget -O go.tgz "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
 && echo "${DIGEST} *go.tgz" | sha256sum -c - \
 &&	tar -C /usr/local -xzf go.tgz \
 && rm go.tgz \
 && export PATH="/usr/local/go/bin:$PATH" \
 && go version

ONBUILD ARG REPOSITORY
ONBUILD ARG PACKAGE
ONBUILD ARG CGO_ENABLED
ONBUILD ENV CGO_ENABLED=${CGO_ENABLED} \
            PACKAGE=${PACKAGE} \
            GO111MODULE=on
ONBUILD WORKDIR /go/src/${REPOSITORY}/
ONBUILD COPY go.mod .
ONBUILD COPY go.sum .
ONBUILD RUN go mod download
ONBUILD COPY . .
ONBUILD RUN /loader -o /app "${PACKAGE:-}"
