#!/bin/sh

set -ue

if [ -n "${1:-}" ]; then
	exec "$@"
fi

LDFLAGS="${LDFLAGS:-}"
CGO_CFLAGS="${CGO_CFLAGS:--g -O2}"
CGO_LDFLAGS="${CGO_LDFLAGS:--g -O2}"
CGO_CXXFLAGS="${CGO_LDFLAGS:--g -O2}"
X=""
if [ -n "$VERBOSE" ]; then
	set -x
	X="-x"
fi

if [ "$#" = 0 ]; then
	echo "Assuming the working directory contains source files." >&2
fi

if [ -n "$TAR" ]; then
	tar -x >&2
	(
	[ -n "${1:-}" ] && [ -d "src/$1" ] && cd "src/$1"
	/usr/local/go/bin/go get -v -d >&2
	)
fi

export CGO_CFLAGS
export CGO_LDFLAGS="$CGO_LDFLAGS"

(
echo "CC=${CC:-}"
echo "CGO_CFLAGS=$CGO_CFLAGS"
echo "CGO_CXXFLAGS=$CGO_CXXFLAGS"
echo "CGO_ENABLED=$CGO_ENABLED"
echo "CGO_LDFLAGS=$CGO_LDFLAGS"
echo "GOARCH=$GOARCH"
echo "LDFLAGS=$LDFLAGS"
echo "PWD=$PWD"
echo Running /bin/go build -v $X "$@"
) >&2
ret=0
/bin/go build -v $X "$@" >&2 || ret=$?
if [ $ret != 0 ]; then
	echo "Exit: $ret" >&2
	exit $ret
fi
if [ -n "$TAR" ]; then
	tar -c .
fi
