#!/bin/bash
set -euo pipefail

IMAGE_NAME=${1:-brimstone/golang}

for f in Dockerfile.*; do
	v="${f##Dockerfile.}"
	docker tag "$IMAGE_NAME:$v" "$IMAGE_NAME:${v%.*}"
done
latest="$(ls Dockerfile.* | sort -r | head -n 1)"
latest="${latest##Dockerfile.}"
docker tag "$IMAGE_NAME:$latest" "$IMAGE_NAME:latest"
docker rmi "$IMAGE_NAME:temp" || true
docker push "$IMAGE_NAME"
